version: '3.7'

services:
  notebook:
    image: jupyter/datascience-notebook:latest
    container_name: gensen-notebook
    environment:
      WORKSPACE: /home/jovyan/work
    ports:
      - '8888:8888'
    volumes:
      - ..:/home/jovyan/work
